package au.com.telstra.simcardactivator.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entity class representing a SIM card record in the database.
 * This class stores information about SIM card activation attempts.
 */
@Entity
@Table(name = "sim_card")
public class SimCard {

    /**
     * Unique identifier for the SIM card record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * The ICCID (Integrated Circuit Card Identifier) of the SIM card.
     */
    @Column(nullable = false)
    private String iccid;
    
    /**
     * The email address of the customer associated with the SIM card.
     */
    @Column(nullable = false)
    private String customerEmail;
    
    /**
     * Flag indicating whether the SIM card was activated successfully.
     */
    @Column(nullable = false)
    private boolean active;

    /**
     * Default constructor required by JPA.
     */
    public SimCard() {
        // Required by JPA
    }

    /**
     * Constructor for creating a new SIM card record.
     * The ID is not included as it's auto-generated by the database.
     *
     * @param iccid the ICCID of the SIM card
     * @param customerEmail the email address of the customer
     * @param active whether the SIM card was activated successfully
     */
    public SimCard(String iccid, String customerEmail, boolean active) {
        this.iccid = iccid;
        this.customerEmail = customerEmail;
        this.active = active;
    }

    /**
     * Gets the ID of the SIM card record.
     *
     * @return the ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the ICCID of the SIM card.
     *
     * @return the ICCID
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * Sets the ICCID of the SIM card.
     *
     * @param iccid the ICCID to set
     */
    public void setIccid(String iccid) {
        this.iccid = iccid;
    }

    /**
     * Gets the email address of the customer.
     *
     * @return the customer's email address
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the email address of the customer.
     *
     * @param customerEmail the customer's email address to set
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    /**
     * Checks if the SIM card was activated successfully.
     *
     * @return true if the SIM card is active, false otherwise
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the activation status of the SIM card.
     *
     * @param active the activation status to set
     */
    public void setActive(boolean active) {
        this.active = active;
    }
}